<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class pureFilipino extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $badWords =  array(
    array("id" => 1, "word" => "abnormal"),
    array("id" => 2, "word" => "adik"),
    array("id" => 3, "word" => "ahas"),
    array("id" => 4, "word" => "abusado"),
    array("id" => 5, "word" => "amputa"),
    array("id" => 6, "word" => "baboy"),
    array("id" => 7, "word" => "bading"),
    array("id" => 8, "word" => "baliw"),
    array("id" => 9, "word" => "balasubas"),
    array("id" => 10, "word" => "bastos"),
    array("id" => 11, "word" => "bastos-na-bastos"),
    array("id" => 12, "word" => "bastos-na-walanghiya"),
    array("id" => 13, "word" => "bastardo"),
    array("id" => 14, "word" => "basura"),
    array("id" => 15, "word" => "basura-ka"),
    array("id" => 16, "word" => "bayag"),
    array("id" => 17, "word" => "bobong-bobo"),
    array("id" => 18, "word" => "bobo"),
    array("id" => 19, "word" => "bogo"),
    array("id" => 20, "word" => "burat"),
    array("id" => 21, "word" => "buhay-hayop"),
    array("id" => 22, "word" => "buhay-na-demonyo"),
    array("id" => 23, "word" => "buwisit"),
    array("id" => 24, "word" => "bilat"),
    array("id" => 25, "word" => "bwisit"),
    array("id" => 26, "word" => "bwisit-na-gago"),
    array("id" => 27, "word" => "bunganga"),
    array("id" => 28, "word" => "obob"),
    array("id" => 29, "word" => "demonyita"),
    array("id" => 30, "word" => "demonyo"),
    array("id" => 31, "word" => "demonyo-ka-talaga"),
    array("id" => 32, "word" => "dugyot"),
    array("id" => 33, "word" => "duwag"),
    array("id" => 34, "word" => "duwag-na-duwag"),
    array("id" => 35, "word" => "gago"),
    array("id" => 36, "word" => "gaga"),
    array("id" => 37, "word" => "gagi"),
    array("id" => 38, "word" => "gago-ka-talaga"),
    array("id" => 39, "word" => "gago-amputa"),
    array("id" => 40, "word" => "gago-ulol"),
    array("id" => 41, "word" => "gunggong"),
    array("id" => 42, "word" => "hambog"),
    array("id" => 43, "word" => "hampaslupa"),
    array("id" => 44, "word" => "hayop"),
    array("id" => 45, "word" => "hayop-ka"),
    array("id" => 46, "word" => "hayop-ka-talaga"),
    array("id" => 47, "word" => "hayup"),
    array("id" => 48, "word" => "hindot"),
    array("id" => 49, "word" => "hinayupak"),
    array("id" => 50, "word" => "hinayupak-ka"),
    array("id" => 51, "word" => "hinayupak-ka-talaga"),
    array("id" => 52, "word" => "hudas"),
    array("id" => 53, "word" => "hudas-barabas"),
    array("id" => 54, "word" => "impyerno"),
    array("id" => 55, "word" => "inutil"),
    array("id" => 56, "word" => "itits"),
    array("id" => 57, "word" => "insulto"),
    array("id" => 58, "word" => "ipokrito"),
    array("id" => 59, "word" => "iyot"),
    array("id" => 60, "word" => "iyot-ka"),
    array("id" => 61, "word" => "judas"),
    array("id" => 62, "word" => "kupaloid"),
    array("id" => 63, "word" => "kupal"),
    array("id" => 64, "word" => "kantot"),
    array("id" => 65, "word" => "kantutan"),
    array("id" => 66, "word" => "lapastangan"),
    array("id" => 67, "word" => "leche"),
    array("id" => 68, "word" => "leche-ka"),
    array("id" => 69, "word" => "leche-ka-talaga"),
    array("id" => 70, "word" => "lecheng-buhay"),
    array("id" => 71, "word" => "letse-flan"),
    array("id" => 72, "word" => "lintik"),
    array("id" => 73, "word" => "lintik-ka"),
    array("id" => 74, "word" => "lintik-na-buhay"),
    array("id" => 75, "word" => "loko"),
    array("id" => 76, "word" => "loko-loko"),
    array("id" => 77, "word" => "lupang-ina"),
    array("id" => 78, "word" => "makapal-na-mukha"),
    array("id" => 79, "word" => "makasarili"),
    array("id" => 80, "word" => "malandi"),
    array("id" => 81, "word" => "malaswa"),
    array("id" => 82, "word" => "malibog"),
    array("id" => 83, "word" => "mangmang"),
    array("id" => 84, "word" => "mangmang-na-mangmang"),
    array("id" => 85, "word" => "manloloko"),
    array("id" => 86, "word" => "manyak"),
    array("id" => 87, "word" => "manyakis"),
    array("id" => 88, "word" => "nimal"),
    array("id" => 89, "word" => "ogag"),
    array("id" => 90, "word" => "ogag-ka"),
    array("id" => 91, "word" => "ogag-na-ogag"),
    array("id" => 92, "word" => "pakyo"),
    array("id" => 93, "word" => "pakyu-pakyu"),
    array("id" => 94, "word" => "pakyut"),
    array("id" => 95, "word" => "palahula"),
    array("id" => 96, "word" => "pangit"),
    array("id" => 97, "word" => "patay-gutom"),
    array("id" => 98, "word" => "peste"),
    array("id" => 99, "word" => "poke"),
    array("id" => 100, "word" => "poki"),
    array("id" => 101, "word" => "pakshet"),
    array("id" => 102, "word" => "pambihira"),
    array("id" => 103, "word" => "putragis"),
    array("id" => 104, "word" => "saksakan"),
    array("id" => 105, "word" => "shet"),
    array("id" => 106, "word" => "shit"),
    array("id" => 107, "word" => "tangina-gago"),
    array("id" => 108, "word" => "tangina-mo"),
    array("id" => 109, "word" => "tangnamo"),
    array("id" => 110, "word" => "ulupong")
);
    DB::table('pure_filipino')->insert($badWords);
    }
}
